[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.server:app --bind 0.0.0.0:$PORT"
restartPolicyType = "never"

[[services]]
name = "web"
source = "."